export const branches = [
    "Aeronautical Engineering",
    "Aerospace Engineering",
    "Applied Mechanics",
    "Automobile Engineering",
    "Biomedical Engineering",
    "Biotechnology Engineering",
    "Chemical Engineering",
    "Chemistry",
    "Ceramic Engineering",
    "Civil Engineering",
    "Computer Science Engineering",
    "Communications Engineering",
    "Construction Engineering",
    'Electrical Engineering',
    "Electronics Engineering",
    "Electronics & Communication Engineering",
    "Engineering Design",
    "Engineering Physics",
    "Environmental Engineering",
    "Humanities and Social Sciences",
    "Industrial Engineering",
    "Management Studies",
    "Marine Engineering",
    "Mathematics",
    "Mechanical Engineering",
    "Mechatronics Engineering",
    "Metallurgical and Materials Engineering",
    "Mining Engineering",
    "Naval Architechture and Ocean Engineering",
    "Petroleum Engineering",
    "Physics",
    "Power Engineering",
    "Production Engineering",
    "Robotics Engineering",
    "Structural Engineering",
    "Transportation Engineering",
    "Telecommunication Engineering",
    "Textile Engineering",
    "Tool Engineering",
    "Other"
]